### ISSUE TITLE
ember 2.2 fails to start concat_with_maps-input_base_path

### ISSUE THREAD

**Issue by vasilakisfil** [benefitcloud/ember-uploader#99]
Just installed this addon but I get this error:
```
ENOENT, no such file or directory '/home/vasilakisfil/videofy/admin-panel/tmp/concat_with_maps-input_base_path-o3AyUCPJ.tmp/0/bower_components/ember-uploader/dist/ember-uploader.named-amd.js'
Error: ENOENT, no such file or directory '/home/vasilakisfil/videofy/admin-panel/tmp/concat_with_maps-input_base_path-o3AyUCPJ.tmp/0/bower_components/ember-uploader/dist/ember-uploader.named-amd.js'
    at Error (native)
    at Object.fs.statSync (fs.js:797:18)
    at ConcatWithMaps.keyForFile (/home/vasilakisfil/videofy/admin-panel/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:90:20)
    at Array.map (native)
    at ConcatWithMaps.CachingWriter._conditionalBuild (/home/vasilakisfil/videofy/admin-panel/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:112:65)
    at /home/vasilakisfil/videofy/admin-panel/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/home/vasilakisfil/videofy/admin-panel/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/home/vasilakisfil/videofy/admin-panel/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/home/vasilakisfil/videofy/admin-panel/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/home/vasilakisfil/videofy/admin-panel/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)

```

Ember 2.2, ember-cli 1.13.14, ember-uploader 0.3.11

What could be wrong ?

**Comment by vasilakisfil** [comment]
Just installed bower install ember-uploader --save and works :+1: 
Why we need bower package apart from ember-cli package ?

**Comment by cybernetlab** [comment]
Same problem, but `bower install ember-uploader --save` doesn't help in my case. And I've another error report:

```
Error: ENOENT: no such file or directory, stat '/work/projects/sferosoft/terminal_admin/tmp/source_map_concat-input_base_path-uCViYp7Y.tmp/0/bower_components/ember-uploader/dist/ember-uploader.named-amd.js'
    at Error (native)
    at Object.fs.statSync (fs.js:892:18)
    at ConcatWithMaps.keyForFile (/work/projects/sferosoft/terminal_admin/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/index.js:90:20)
    at Array.map (native)
    at ConcatWithMaps.CachingWriter._conditionalBuild (/work/projects/sferosoft/terminal_admin/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/index.js:112:65)
    at /work/projects/sferosoft/terminal_admin/node_modules/broccoli-concat/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/work/projects/sferosoft/terminal_admin/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/work/projects/sferosoft/terminal_admin/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/work/projects/sferosoft/terminal_admin/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/work/projects/sferosoft/terminal_admin/node_modules/rsvp/dist/rsvp.js:1198:9)
```

**Comment by cybernetlab** [comment]
Sorry - my mistake - I forgot to remove old `ember-cli-uploader` dependency from my `package.json`.
